export default [
  "Get 16 matching Wool blocks",
  "Get 8 unique Wool blocks",
  "Get 8 matching Terracotta blocks",
  "Get 4 unique Terracotta blocks",
  "Get 16 matching Concrete blocks",
  "Get 8 unique Concrete blocks",
  "Get 16 matching Glass blocks",
  "Get 8 unique Glass blocks",
  "Get 16 Eggs",
  "Get 32 Leather",
  "Get 32 Porkchops",
  "Get 3 buckets of Milk",
  "Get 16 total raw fish",
  "Get 4 Ender Pearls",
  "Get 32 Rotten Flesh",
  "Get 32 Bones",
  "Get 32 Arrows",
  "Get 16 Gunpowder",
  "Get 8 Slimeballs",
  "Get 32 String",
  "Get 8 different Dyes",
  "Get a Rabbit drop",
  "Get 32 Sugar Cane",
  "Get 8 Pumpkins",
  "Get 8 Melons",
  "Get 32 Wheat",
  "Get 16 Carrots",
  "Get 16 Potatoes",
  "Get 8 Obsidian",
  "Get 16 Beetroots",
  "Get 16 Cocoa Beans",
  "Get 3 Bottles of Honey",
  "Get 32 matching logs",
  "Get 64 matching planks",
  "Get 4 unique saplings",
  "Get 8 Apples",
  "Get 32 Coal",
  "Get 32 Iron ingots",
  "Get 16 Gold ingots",
  "Get 8 Diamonds",
  "Get 32 Redstone Dust",
  "Get 32 Lapis Lazuli",
  "Get 64 Dirt",
  "Get 64 Cobblestone",
  "Get 64 Andesite",
  "Get 64 Granite",
  "Get 64 Diorite",
  "Get 64 Sand",
  "Get 8 Cactus blocks",
  "Get 16 Charcoal",
  "Get 16 Copper ingots",
  "Get 8 Feathers",
  "Get an Emerald",
  "Get a Leaf block",
  "Get a Lily Pad",
  "Get 16 Stone (not cobble)",
  "Get 16 Glass",
  "Get a mob head",
  "Get 8 unique flowers",
  "Get a Saddle",
  "Get a player's head",
  "Get 32 Bamboo",
  "Craft a Piston",
  "Craft a Sticky Piston",
  "Craft a Dispenser",
  "Craft a Crafter",
  "Craft a Book and Quill",
  "Craft all Iron armor",
  "Craft 5 unique Iron tools",
  "Craft a Diamond pickaxe",
  "Craft a Diamond sword",
  "Craft a Diamond hoe",
  "Craft a Diamond shovel",
  "Craft a Diamond axe",
  "Craft a Gold chestplate",
  "Craft 3 unique Gold tools",
  "Craft Gold boots",
  "Craft a Shield",
  "Craft an anvil",
  "Craft an armor stand",
  "Craft a Bookshelf",
  "Craft a Cake",
  "Craft a Hopper",
  "Craft a Jukebox",
  "Craft a Note Block",
  "Craft a Redstone Repeater",
  "Craft a Spyglass",
  "Craft a Stonecutter",
  "Craft a Brush",
  "Craft an Enchanting Table",
  "Craft a Target",
  "Breed Cows",
  "Breed Sheep",
  "Breed Pigs",
  "Breed Chickens",
  "Hatch a Chicken from an Egg",
  "Breed Wolves (Dogs)",
  "Bounce on a Slime block",
  "Stick to a Honey block",
  "Break a tool",
  "Breed Bees",
  "Sleep in a bed",
  "Wear a Carved Pumpkin",
  "Cook on a Campfire",
  "Use a brush at a dig site",
  "Drink milk",
  "Die",
  "Dye a Sheep",
  "Eat a Baked Potato",
  "Eat some Rotten Flesh",
  "Eat a piece of Bread",
  "Enchant something",
  "Fill a Composter",
  "Kill an Enderman",
  "Kill a Zombie",
  "Kill a Skeleton",
  "Kill a Creeper",
  "Kill any Illager",
  "Kill a Horse",
  "Kill 4 Chickens",
  "Kill 4 Sheep",
  "Kill 4 Cows",
  "Kill 4 Pigs",
  "Get a miniblock from a Wandering Trader",
  "Kill a Spider",
  "Kill a Slime",
  "Kill a Squid",
  "Die from lava",
  "Die from fall damage",
  "Ingite a Creeper with Flint & Steel",
  "Ignite TNT with redstone",
  "Plant a seed",
  "Plant a sapling",
  "Play a music disc",
  "Put a mob head on a Note Block",
  "Reach build height (Y 320)",
  "Stand on Bedrock",
  "Rename an item in an anvil",
  "Ride a Minecart on a Rail",
  "Ring a Bell",
  "Set your spawn",
  "Shear a Sheep",
  "Use a Spyglass",
  "Strip a log",
  "Tame a Horse",
  "Ride a Horse",
  "Throw an Ender Pearl",
  "Throw a Snowball",
  "Throw an Egg",
  "Write and sign a book",
  "Find a coral reef",
  "Find an Ocean Monument",
]
