export default [
  "Get 16 matching Wool blocks",
  "Get 8 unique Wool blocks",
  "Get 16 matching Terracotta blocks",
  "Get 8 unique Terracotta blocks",
  "Get 16 matching Concrete blocks",
  "Get 8 unique Concrete blocks",
  "Get 16 matching Glass blocks",
  "Get 8 unique Glass blocks",
  "Get 16 Eggs",
  "Get 32 Leather",
  "Get 32 Porkchops",
  "Get 3 buckets of Milk",
  "Get 16 total raw fish",
  "Get 8 Ender Pearls",
  "Get 64 Rotten Flesh",
  "Get 64 Bones",
  "Get 64 Arrows",
  "Get 32 Gunpowder",
  "Get 16 Slimeballs",
  "Get 32 String",
  "Get 8 different Dyes",
  "Get 8 total Rabbit drops",
  "Get 64 Sugar Cane",
  "Get 16 Pumpkins",
  "Get 16 Melons",
  "Get 64 Wheat",
  "Get 64 Carrots",
  "Get 64 Potatoes",
  "Get a Nether Wart",
  "Get 8 Obsidian",
  "Get 64 Beetroots",
  "Get 16 Cocoa Beans",
  "Get 3 Bottles of Honey",
  "Get 64 matching logs",
  "Get 64 matching planks",
  "Get 5 unique saplings",
  "Get 16 Apples",
  "Get 64 Coal",
  "Get 64 Iron ingots",
  "Get 32 Gold ingots",
  "Get 16 Diamonds",
  "Get 64 Redstone Dust",
  "Get 64 Lapis Lazuli",
  "Get 64 Dirt",
  "Get 64 Cobblestone",
  "Get 64 Andesite",
  "Get 64 Granite",
  "Get 64 Diorite",
  "Get a Blaze Rod",
  "Get 64 Sand",
  "Get 4 Glowstone blocks",
  "Get 16 Cactus blocks",
  "Get 64 Charcoal",
  "Get 48 Copper ingots",
  "Get 16 Feathers",
  "Get 16 Emeralds",
  "Get 64 Leaves",
  "Get 8 Lily Pads",
  "Get 64 Netherrack",
  "Get 32 Nether Quartz",
  "Get 64 Stone (not cobble)",
  "Get 64 Glass",
  "Get a passive or neutral mob head",
  "Get a Glow Ink Sac",
  "Get a Goat Horn",
  "Get 10 unique flowers",
  "Get a Saddle",
  "Get a Trident",
  "Get a hostile mob head",
  "Get a player's head",
  "Get a Nautilus Shell",
  "Get 64 Bamboo",
  "Craft a Piston",
  "Craft a Sticky Piston",
  "Craft a Dispenser",
  "Craft a Crafter",
  "Craft a Book and Quill",
  "Craft all Iron armor",
  "Craft 5 unique Iron tools",
  "Craft a Diamond pickaxe",
  "Craft a Diamond sword",
  "Craft a Diamond hoe",
  "Craft a Diamond shovel",
  "Craft a Diamond axe",
  "Craft a Gold chestplate",
  "Craft 3 unique Gold tools",
  "Craft Gold boots",
  "Craft a Shield",
  "Craft an anvil",
  "Craft an armor stand",
  "Craft a Bookshelf",
  "Craft a Cake",
  "Craft a Hopper",
  "Craft a Jukebox",
  "Craft a Note Block",
  "Craft a Redstone Comparator",
  "Craft a Redstone Repeater",
  "Craft a Spyglass",
  "Craft a Stonecutter",
  "Craft a Brush",
  "Craft an Enchanting Table",
  "Craft a Target",
  "Breed Cows",
  "Breed Sheep",
  "Breed Pigs",
  "Breed Chickens",
  "Hatch a Chicken from an Egg",
  "Breed Wolves (dogs)",
  "Bounce on a Slime block",
  "Stick to a Honey block",
  "Break a tool",
  "Breed Bees",
  "Sleep in a bed",
  "Blow up a bed",
  "Use a Cauldron to clean dye",
  "Put a full map in a frame",
  "Wear a Carved Pumpkin",
  "Cook on a Campfire",
  "Use a brush at a dig site",
  "Drink milk",
  "Die",
  "Dye a Sheep",
  "Eat a Baked Potato",
  "Eat a Golden Carrot",
  "Eat some Rotten Flesh",
  "Eat a piece of Bread",
  "Eat a Golden Apple",
  "Eat a Cookie",
  "Enchant something",
  "Fill a Composter",
  "Get mining fatigue",
  "Grow a Dark Oak tree",
  "Kill yourself with an arrow",
  "Kill an Enderman",
  "Kill a Zombie",
  "Kill a Skeleton",
  "Kill a Creeper",
  "Kill any Illager",
  "Kill a Horse",
  "Kill a Drowned",
  "Kill a Husk",
  "Equip full Leather armor",
  "Get the Hunger effect",
  "Grow a large Jungle tree",
  "Kill a Bee",
  "Kill a Cave Spider",
  "Kill 4 Chickens",
  "Kill 4 Sheep",
  "Kill 4 Cows",
  "Kill 4 Pigs",
  "Kill a Glow Squid",
  "Die to an Iron Golem",
  "Be spit on by a llama",
  "Kill a Wandering Trader",
  "Get a miniblock from a Wandering Trader",
  "Kill a Rabbit",
  "Tame a wolf",
  "Kill a mob so it drops COOKED meat",
  "Kill a Witch",
  "Kill a Wolf",
  "Kill a Spider",
  "Kill a Snow Golem",
  "Kill a Slime",
  "Kill a Squid",
  "Kill a Villager",
  "Kill a Zombie Villager",
  "Die from lava",
  "Die from fall damage",
  "Ingite a Creeper with Flint & Steel",
  "Ignite TNT with redstone",
  "Enter the Nether",
  "Plant a seed",
  "Plant a sapling",
  "Play a music disc",
  "Put a mob head on a Note Block",
  "Reach Y 320",
  "Stand on Bedrock",
  "Rename an item in an anvil",
  "Ride a Minecart on a Rail",
  "Ring a Bell",
  "Set your spawn",
  "Shear a Sheep",
  "Use a Spyglass",
  "Strip a log",
  "Tame a Horse",
  "Ride a Horse",
  "Throw a Diamond into lava",
  "Throw an Ender Pearl",
  "Throw a Snowball",
  "Throw an Egg",
  "Trap any mob in a boat",
  "Use any dye on a sign",
  "Write and sign a book",
  "Use Bone Meal on Grass",
  "Find a Frog",
  "Find a biome with Ice",
  "Find a Cat",
  "Find a Village",
  "Find a Desert Temple",
  "Find a mineshaft",
  "Find a dungeon spawner",
  "Find a coral reef",
  "Find an Ocean Monument",
  "Find any Smithing Template",
  "Find an Igloo",
  "Find a badlands biome",
  "Find a dripstone cave",
  "Find a Swamp",
  "Find a Bamboo biome",
  "Find a Mangrove Swamp",
  "Find a ravine",
  "Find a shipwreck",
  "Find a dig site",
  "Find a biome with Snow",
  "Find an Amythyst geode",
  "Find a Deep Dark biome",
  "See two Skeletons shoot each other",
  "Find a Ruined Portal",
  "Find buried treasure",
  "Find horse armor",
]
